name: CI

on: [push]

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        ruby: [ "3.2", "3.1", "3.0" ]
        gemfile: [ "active_job_71.gemfile", "active_job_70.gemfile", "active_job_61.gemfile", "active_job_60.gemfile" ]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        # Wait for starting Redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile}}

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        bundle install
    - name: Run test
      run: bundle exec rake
